### ISSUE TITLE
Use another LSTM data format instead of JSON

### ISSUE THREAD

**Issue by makotokato** [aethanyc/icu4x#3]
Actually, LSTM's binary format (*.npy) depends on TensorFlow. LSTM team suggests that we can create other format (see  https://github.com/unicode-org/lstm_word_segmentation/issues/16).  So I should use rust data type or any format instead of JSON via `build.rs`.

**Comment by aethanyc** [comment]
This is a dup of https://github.com/unicode-org/icu4x/issues/905.
